project:
  type: website

website:
  title: "AAA:  Applied Anime Analytics"
  navbar:
    left:
      - href: index.md
        text: Home
      - src/exploracion_inicial.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true